global:
  scrape_interval: 15s

scrape_configs:
  - job_name: demo-app
    static_configs:
      - targets: ["stinky-socks:9100"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerts.yml
