{
 "title": "PR metrics",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team_name",
    "label": "Team",
    "query": "SELECT DISTINCT team_name \nFROM pull_request\nWHERE pull_request.integrity_errors IS NULL\nORDER BY team_name"
   },
   {
    "name": "repository_name",
    "label": "Repository name",
    "query": "SELECT DISTINCT (repository_name) \nFROM pull_request \nWHERE \n    pull_request.integrity_errors IS NULL\n    AND $__timeFilter(shared_for_review_date) \n    AND (COALESCE($team_name) IS NULL OR team_name IN ($team_name))    \nORDER BY repository_name"
   },
   {
    "name": "pr_author_role",
    "label": "Author role",
    "query": "SELECT \nDISTINCT author_role\nFROM pull_request \n    INNER JOIN contributor ON pull_request.author_id = contributor.id\nWHERE pull_request.integrity_errors IS NULL\n    AND $__timeFilter(shared_for_review_date) \n    AND (COALESCE($team_name) IS NULL OR pull_request.team_name IN ($team_name))    \n    AND (COALESCE($repository_name) IS NULL OR repository_name IN ($repository_name))"
   },
   {
    "name": "pr_author",
    "label": "PR author",
    "query": "SELECT \nDISTINCT \ncontributor.id as __value, \nCASE WHEN $show_real_names THEN contributor.login ELSE contributor.nickname END as __text \nFROM pull_request \n    INNER JOIN contributor ON pull_request.author_id = contributor.id\nWHERE pull_request.integrity_errors IS NULL\n    AND $__timeFilter(shared_for_review_date) \n    AND (COALESCE($team_name) IS NULL OR pull_request.team_name IN ($team_name))    \n    AND (COALESCE($repository_name) IS NULL OR repository_name IN ($repository_name))\n    AND (COALESCE($pr_author_role) IS NULL OR pull_request.author_role IN ($pr_author_role))\nORDER BY 2"
   },
   {
    "name": "group_by_field",
    "label": "Group by",
    "query": "Repository : repository_name, Author : author"
   },
   { "name": "include_bots_activities", "label": "Include bots activities", "query": "No : False,Yes : True" },
   {
    "name": "percent_of_outliers_to_exclude",
    "label": "Percentage of outliers to exclude",
    "query": "0% : 0, +/-1% : 0.01, +/-3% : 0.03, +/-5% : 0.05, +/-10% : 0.1"
   },
   {
    "name": "group_by_period",
    "label": "Group by period",
    "query": "Days : 1d,  Weeks : 1w, Months : 1M, Quarters : 3M, Years : 1y"
   },
   { "name": "show_real_names", "label": "Show real names", "query": "False" }
  ]
 },
 "panels": [
  { "title": "Flow stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lead Time (from the first commit to pull request merge), excluding outliers ($percent_of_outliers_to_exclude)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(pr_lead_time) AS \"Average lead time\"\nFROM \n   (SELECT \n      EXTRACT(EPOCH FROM (merged_date-initial_commit_date)) AS pr_lead_time,\n      PERCENT_RANK() OVER (ORDER BY EXTRACT(EPOCH FROM (merged_date-initial_commit_date))) AS value_rank\n   FROM pull_request AS pr\n      INNER JOIN contributor as author ON author.id = pr.author_id\n   WHERE pr.integrity_errors IS NULL\n      AND $__timeFilter(shared_for_review_date) \n      AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n      AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n      AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n      AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n      AND ($include_bots_activities OR NOT author.is_bot_user)\n   ) AS lead_times\nWHERE value_rank BETWEEN (0+$percent_of_outliers_to_exclude) AND (1-$percent_of_outliers_to_exclude)\n"
    }
   ]
  },
  {
   "title": "Development time, excluding outliers ($percent_of_outliers_to_exclude)",
   "type": "stat",
   "description": "From the first commit to PR raised",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(from_commit_to_share) AS \"Development time\"\nFROM \n   (SELECT \n      GREATEST(EXTRACT(EPOCH FROM (shared_for_review_date-initial_commit_date)),0) AS from_commit_to_share,\n      PERCENT_RANK() OVER (ORDER BY GREATEST(EXTRACT(EPOCH FROM (shared_for_review_date-initial_commit_date)),0)) AS value_rank\n   FROM pull_request AS pr\n      INNER JOIN contributor as author ON author.id = pr.author_id\n   WHERE pr.integrity_errors IS NULL\n      AND $__timeFilter(shared_for_review_date) \n      AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n      AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n      AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n      AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n      AND ($include_bots_activities OR NOT author.is_bot_user)\n   ) AS timings\nWHERE value_rank BETWEEN (0+$percent_of_outliers_to_exclude) AND (1-$percent_of_outliers_to_exclude)\n"
    }
   ]
  },
  {
   "title": "Time to first reaction, excluding outliers ($percent_of_outliers_to_exclude)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(time_to_first_response) AS \"Time to first reactions\"\nFROM (\n    SELECT\n        GREATEST(EXTRACT(EPOCH FROM (first_reaction_date-shared_for_review_date)), 0) AS time_to_first_response,\n        PERCENT_RANK() OVER (ORDER BY GREATEST(EXTRACT(EPOCH FROM (first_reaction_date-shared_for_review_date)), 0)) AS value_rank\n   FROM pull_request AS pr\n      INNER JOIN contributor as author ON author.id = pr.author_id\n   WHERE pr.integrity_errors IS NULL\n      AND $__timeFilter(shared_for_review_date) \n      AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n      AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n      AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n      AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n      AND ($include_bots_activities OR NOT author.is_bot_user)\n      AND first_reaction_date IS NOT NULL\n    ) AS \"First responses\"\nWHERE value_rank BETWEEN (0+$percent_of_outliers_to_exclude) AND (1-$percent_of_outliers_to_exclude)"
    }
   ]
  },
  {
   "title": "Rework time, excluding outliers ($percent_of_outliers_to_exclude)",
   "type": "stat",
   "description": "Time from the first reaction to PR merge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(rework_time)\nFROM (\n    SELECT\n        GREATEST(EXTRACT(EPOCH FROM (rework_completed_date-first_reaction_date)), 0) AS rework_time,\n        PERCENT_RANK() OVER (ORDER BY GREATEST(EXTRACT(EPOCH FROM (rework_completed_date-first_reaction_date)), 0)) AS value_rank\n    FROM pull_request AS pr\n        INNER JOIN contributor as author ON author.id = pr.author_id\n    WHERE pr.integrity_errors IS NULL\n      AND $__timeFilter(shared_for_review_date) \n      AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n      AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n      AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n      AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n      AND ($include_bots_activities OR NOT author.is_bot_user)\n      AND first_reaction_date IS NOT NULL\n      AND rework_completed_date IS NOT NULL\n) AS rework_times\nWHERE value_rank BETWEEN (0+$percent_of_outliers_to_exclude) AND (1-$percent_of_outliers_to_exclude)"
    }
   ]
  },
  {
   "title": "Idle between pull request approval and merge, excluding outliers ($percent_of_outliers_to_exclude)",
   "type": "stat",
   "description": "Time from last approve to PR merge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(from_last_approve_to_merge)\nFROM (\n    SELECT\n        EXTRACT(EPOCH FROM (merged_date-last_action_date)) AS from_last_approve_to_merge,\n        PERCENT_RANK() OVER (ORDER BY EXTRACT(EPOCH FROM (merged_date-last_action_date))) AS value_rank\n    FROM (\n            SELECT\n                merged_date,\n                GREATEST(pr.last_approval_date, pr.rework_completed_date, pr.last_commit_date) as last_action_date\n            FROM pull_request AS pr\n                INNER JOIN pull_request_participant AS prtcpnt ON pr.project_name = prtcpnt.project_name AND pr.repository_name = prtcpnt.repository_name AND pr.pull_request_number = prtcpnt.pull_request_number\n                INNER JOIN contributor as author ON author.id = pr.author_id\n            WHERE pr.integrity_errors IS NULL\n                AND $__timeFilter(shared_for_review_date) \n                AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n                AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n                AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n                AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n                AND ($include_bots_activities OR NOT author.is_bot_user)\n        ) AS approvals\n) AS timings\nWHERE value_rank BETWEEN (0+$percent_of_outliers_to_exclude) AND (1-$percent_of_outliers_to_exclude)"
    }
   ]
  },
  {
   "title": "Flow time stats by $group_by_period",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT \n$__timeGroupAlias(shared_for_review_date, $group_by_period), \nAVG(pr_lead_time) AS \"Average lead time\"\nFROM \n   (SELECT \n      shared_for_review_date,\n      EXTRACT(EPOCH FROM (merged_date-initial_commit_date)) AS pr_lead_time,\n      PERCENT_RANK() OVER (ORDER BY EXTRACT(EPOCH FROM (merged_date-initial_commit_date))) AS value_rank\n   FROM pull_request AS pr\n      INNER JOIN contributor as author ON author.id = pr.author_id\n   WHERE pr.integrity_errors IS NULL\n      AND $__timeFilter(shared_for_review_date) \n      AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n      AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n      AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n      AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n      AND ($include_bots_activities OR NOT author.is_bot_user)\n   ) AS lead_times\nWHERE value_rank BETWEEN (0+$percent_of_outliers_to_exclude) AND (1-$percent_of_outliers_to_exclude)\nGROUP BY 1\nORDER BY $__timeGroup(shared_for_review_date, $group_by_period, 0)"
    },
    {
     "rawSql": "SELECT \n$__timeGroupAlias(shared_for_review_date, $group_by_period), \nAVG(from_commit_to_raise) AS \"Development time\"\nFROM \n   (SELECT \n      shared_for_review_date,\n      GREATEST(EXTRACT(EPOCH FROM (shared_for_review_date-initial_commit_date)),0) AS from_commit_to_raise,\n      PERCENT_RANK() OVER (ORDER BY EXTRACT(EPOCH FROM (shared_for_review_date-initial_commit_date))) AS value_rank\n   FROM pull_request AS pr\n      INNER JOIN contributor as author ON author.id = pr.author_id\n   WHERE pr.integrity_errors IS NULL\n      AND $__timeFilter(shared_for_review_date) \n      AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n      AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n      AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n      AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n      AND ($include_bots_activities OR NOT author.is_bot_user)\n   ) AS lead_times\nWHERE value_rank BETWEEN (0+$percent_of_outliers_to_exclude) AND (1-$percent_of_outliers_to_exclude)\nGROUP BY 1\nORDER BY $__timeGroup(shared_for_review_date, $group_by_period, 0)"
    },
    {
     "rawSql": "SELECT \n$__timeGroupAlias(shared_for_review_date, $group_by_period), \nAVG(time_to_first_response) AS \"Time to first reaction\" \nFROM (\n    SELECT\n        shared_for_review_date,\n        GREATEST(EXTRACT(EPOCH FROM (first_reaction_date-shared_for_review_date)), 0) AS time_to_first_response,\n        PERCENT_RANK() OVER (ORDER BY GREATEST(EXTRACT(EPOCH FROM (first_reaction_date-shared_for_review_date)), 0)) AS value_rank\n    FROM pull_request AS pr\n        INNER JOIN contributor as author ON author.id = pr.author_id\n    WHERE pr.integrity_errors IS NULL\n        AND $__timeFilter(shared_for_review_date) \n        AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n        AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n        AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n        AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n        AND ($include_bots_activities OR NOT author.is_bot_user)\n        AND first_reaction_date IS NOT NULL\n    ) AS timings\nWHERE value_rank BETWEEN (0+$percent_of_outliers_to_exclude) AND (1-$percent_of_outliers_to_exclude)\nGROUP BY 1\nORDER BY $__timeGroup(shared_for_review_date, $group_by_period, 0)"
    },
    {
     "rawSql": "SELECT \n$__timeGroupAlias(shared_for_review_date, $group_by_period), \nAVG(rework_time) AS \"Rework time\"\nFROM (\n    SELECT\n        shared_for_review_date,\n        EXTRACT(EPOCH FROM (rework_completed_date-first_reaction_date)) AS rework_time,\n        PERCENT_RANK() OVER (ORDER BY EXTRACT(EPOCH FROM (rework_completed_date-first_reaction_date))) AS value_rank\n    FROM pull_request AS pr\n        INNER JOIN contributor as author ON author.id = pr.author_id\n    WHERE pr.integrity_errors IS NULL\n        AND $__timeFilter(shared_for_review_date) \n        AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n        AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n        AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n        AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n        AND ($include_bots_activities OR NOT author.is_bot_user)\n        AND first_reaction_date IS NOT NULL\n        AND rework_completed_date IS NOT NULL\n) AS timings\nWHERE value_rank BETWEEN (0+$percent_of_outliers_to_exclude) AND (1-$percent_of_outliers_to_exclude)\nGROUP BY 1\nORDER BY $__timeGroup(shared_for_review_date, $group_by_period, 0)"
    },
    {
     "rawSql": "SELECT \n    $__timeGroupAlias(shared_for_review_date, $group_by_period), \n    AVG(from_last_action_to_merge) AS \"Idle after approve\"\nFROM (\n    SELECT\n        shared_for_review_date,\n        EXTRACT(EPOCH FROM (merged_date-last_action_date)) AS from_last_action_to_merge,\n        PERCENT_RANK() OVER (ORDER BY EXTRACT(EPOCH FROM (merged_date-last_action_date))) AS value_rank\n    FROM (\n            SELECT\n                shared_for_review_date,\n                merged_date,\n                GREATEST(pr.last_approval_date, pr.rework_completed_date, pr.last_commit_date) as last_action_date\n            FROM pull_request AS pr\n                INNER JOIN pull_request_participant AS prtcpnt ON pr.project_name = prtcpnt.project_name AND pr.repository_name = prtcpnt.repository_name AND pr.pull_request_number = prtcpnt.pull_request_number\n                INNER JOIN contributor as author ON author.id = pr.author_id\n            WHERE pr.integrity_errors IS NULL\n                AND $__timeFilter(shared_for_review_date) \n                AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n                AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n                AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n                AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n                AND ($include_bots_activities OR NOT author.is_bot_user)\n        ) AS actions\n) AS timings\nWHERE value_rank BETWEEN (0+$percent_of_outliers_to_exclude) AND (1-$percent_of_outliers_to_exclude)\nGROUP BY 1\nORDER BY $__timeGroup(shared_for_review_date, $group_by_period, 0)"
    }
   ]
  },
  { "title": "Quantitative traits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pull requests count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`stinky-socks`",
     "rawSql": "SELECT COUNT(*) as \"Average PR size\"\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)"
    }
   ]
  },
  {
   "title": "Average reviewers count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`stinky-socks`",
     "rawSql": "SELECT AVG(reviewers_count) AS \"Reviewers count\" \nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)"
    }
   ]
  },
  {
   "title": "Average comments count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`stinky-socks`",
     "rawSql": "SELECT AVG(total_comments_count) AS \"Comments count\" \nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)"
    }
   ]
  },
  {
   "title": "Average diff size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`stinky-socks`",
     "rawSql": "SELECT avg(diff_size) as \"Average PR size\"\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)"
    }
   ]
  },
  {
   "title": "PRs without tests touch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`stinky-socks`",
     "rawSql": "SELECT SUM(CASE WHEN tests_were_touched THEN 0 ELSE 1 END)::decimal/COUNT(*)*100 AS \"PRs without tests touch\" \nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)"
    }
   ]
  },
  {
   "title": "Total diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`stinky-socks`",
     "rawSql": "SELECT SUM(diff_size) as \"Total diff\"\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)"
    }
   ]
  },
  {
   "title": "Quantitative traits by $group_by_period",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n   $__timeGroupAlias(shared_for_review_date, $group_by_period),\n   COUNT(*) AS \"PRs count\",\n   AVG(reviewers_count) AS \"Reviewers count\",\n   AVG(total_comments_count) AS \"Comments count\",\n   AVG(diff_size) AS \"Diff size\",\n   SUM(CASE WHEN tests_were_touched THEN 0 ELSE 1 END)::decimal/COUNT(*)*100 AS \"PRs without tests changes\",\n   SUM(diff_size) as \"Lines changed\"\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\nGROUP BY 1\nORDER BY $__timeGroup(shared_for_review_date, $group_by_period)"
    }
   ]
  },
  { "title": "Activity traits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Most wanted reviewers",
   "type": "barchart",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT \n   CASE \n      WHEN participant.is_former_employee THEN CONCAT(participant.login, ' (former employee)') \n      WHEN participant.is_bot_user THEN CONCAT(participant.login, ' (bot)')\n      ELSE CASE WHEN $show_real_names THEN participant.login ELSE participant.nickname END\n   END,\n   COUNT(prtcpnt.pull_request_number) AS \"Added as reviewer\",\n   SUM(CASE WHEN prtcpnt.first_comment_date IS NULL AND prtcpnt.first_approval_date IS NOT NULL THEN 1 ELSE 0 END) AS \"Did not comment\",\n   SUM(CASE WHEN prtcpnt.first_approval_date IS NULL THEN 1 ELSE 0 END) AS \"Did not approve\"\nFROM pull_request AS pr\n   INNER JOIN pull_request_participant as prtcpnt ON pr.project_name = prtcpnt.project_name AND pr.repository_name = prtcpnt.repository_name AND pr.pull_request_number = prtcpnt.pull_request_number\n   INNER JOIN contributor as author ON author.id = pr.author_id\n   INNER JOIN contributor as participant ON participant.id = prtcpnt.participant_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\n   AND ($include_bots_activities OR NOT participant.is_bot_user)\nGROUP BY participant.nickname, participant.is_bot_user, participant.is_former_employee, participant.login\nORDER BY \"Added as reviewer\" DESC\n"
    }
   ]
  },
  {
   "title": "Most active reviewers",
   "type": "barchart",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT \n      CASE \n        WHEN participant.is_former_employee THEN CONCAT(participant.login, ' (former employee)') \n        WHEN participant.is_bot_user THEN CONCAT(participant.login, ' (bot)')\n        ELSE CASE WHEN $show_real_names THEN participant.login ELSE participant.nickname END\n      END,\n      AVG(prtcpnt.comments_count) AS \"Average comments count\",\n      AVG(EXTRACT(EPOCH FROM (LEAST(COALESCE(prtcpnt.first_approval_date, prtcpnt.first_comment_date), COALESCE(prtcpnt.first_comment_date, prtcpnt.first_approval_date))-shared_for_review_date))) AS \"First reaction in\"\nFROM pull_request AS pr\n  INNER JOIN pull_request_participant as prtcpnt ON pr.project_name = prtcpnt.project_name AND pr.repository_name = prtcpnt.repository_name AND pr.pull_request_number = prtcpnt.pull_request_number\n  INNER JOIN contributor as author ON author.id = pr.author_id\n  INNER JOIN contributor as participant ON participant.id = prtcpnt.participant_id\nWHERE pr.integrity_errors IS NULL\n  AND $__timeFilter(shared_for_review_date) \n  AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n  AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n  AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n  AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n  AND ($include_bots_activities OR NOT author.is_bot_user)\n  AND ($include_bots_activities OR NOT participant.is_bot_user)\nGROUP BY participant.nickname, participant.is_bot_user, participant.is_former_employee, participant.login\nORDER BY \"First reaction in\"\n"
    }
   ]
  },
  {
   "title": "Top contributors per repository",
   "type": "barchart",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT personal.repository_name, contributor_name, personal_contribution::numeric/total_contribution*100 as \"contribution_percent\"\nFROM\n    (SELECT \n        repository_name, \n        CASE \n            WHEN author.is_former_employee THEN CONCAT(author.login, ' (former employee)') \n            WHEN author.is_bot_user THEN CONCAT(author.login, ' (bot)')\n            ELSE CASE WHEN $show_real_names THEN author.login ELSE author.nickname END\n        END AS contributor_name,\n        SUM(diff_size) as personal_contribution\n    FROM pull_request AS pr\n        INNER JOIN contributor as author ON author.id = pr.author_id\n    WHERE pr.integrity_errors IS NULL\n      AND $__timeFilter(shared_for_review_date) \n      AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n      AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n      AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n      AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n      AND ($include_bots_activities OR NOT author.is_bot_user)\n    GROUP BY repository_name, author.nickname, author.is_former_employee, author.is_bot_user, author.login) AS personal\n\nRIGHT JOIN \n    (SELECT repository_name, SUM(diff_size) as total_contribution\n    FROM pull_request AS pr\n        INNER JOIN contributor as author ON author.id = pr.author_id\n    WHERE pr.integrity_errors IS NULL\n      AND $__timeFilter(shared_for_review_date) \n      AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n      AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n      AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n      AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n      AND ($include_bots_activities OR NOT author.is_bot_user)\n    GROUP BY repository_name) AS total\nON total.repository_name=personal.repository_name\nORDER BY personal.repository_name"
    }
   ]
  },
  {
   "title": "Typical PR timings (including outliers)",
   "type": "barchart",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT \n  grouping_field AS \"$group_by_field\",\n  AVG((GREATEST(EXTRACT(EPOCH FROM (shared_for_review_date-initial_commit_date)), 0))) AS \"Development time\",\n  AVG(EXTRACT(EPOCH FROM (first_reaction_date-shared_for_review_date))) AS \"First reaction got in\",\n  AVG(EXTRACT(EPOCH FROM (rework_completed_date-first_reaction_date))) AS \"Rework time\",\n  AVG(EXTRACT(EPOCH FROM (merged_date-last_action_date))) AS \"Idle after approve\"\nFROM (SELECT\n        CASE WHEN '$group_by_field'='author' \n          THEN\n            CASE \n              WHEN author.is_former_employee THEN CONCAT(author.login, ' (former employee)') \n              WHEN author.is_bot_user THEN CONCAT(author.login, ' (bot)')\n              ELSE CASE WHEN $show_real_names THEN author.login ELSE author.nickname END\n            END\n          ELSE pr.repository_name \n        END as grouping_field,\n        pr.merged_date,\n        pr.shared_for_review_date,\n        pr.initial_commit_date,\n        pr.first_reaction_date,\n        pr.rework_completed_date,\n        GREATEST(pr.last_approval_date, pr.rework_completed_date, pr.last_commit_date) as last_action_date\n    FROM pull_request AS pr\n        INNER JOIN pull_request_participant AS prtcpnt ON pr.project_name = prtcpnt.project_name AND pr.repository_name = prtcpnt.repository_name AND pr.pull_request_number = prtcpnt.pull_request_number\n        INNER JOIN contributor as author ON author.id = pr.author_id\n    WHERE pr.integrity_errors IS NULL\n      AND $__timeFilter(shared_for_review_date) \n      AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n      AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n      AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n      AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n      AND ($include_bots_activities OR NOT author.is_bot_user)\n    GROUP BY 1, pr.project_name, pr.repository_name, pr.pull_request_number\n) AS activity_stats\nGROUP BY 1\nORDER BY AVG((GREATEST(EXTRACT(EPOCH FROM (shared_for_review_date-initial_commit_date)), 0)))\n        +AVG(EXTRACT(EPOCH FROM (first_reaction_date-shared_for_review_date)))\n        +AVG(EXTRACT(EPOCH FROM (rework_completed_date-first_reaction_date)))\n        +AVG(EXTRACT(EPOCH FROM (merged_date-last_action_date)))\n"
    }
   ]
  },
  {
   "title": "Per $group_by_field glance stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 }
  },
  {
   "title": "Total PRs count",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "`stinky-socks`",
     "rawSql": "SELECT \n   CASE WHEN '$group_by_field'='author' \n      THEN\n         CASE \n           WHEN author.is_former_employee THEN CONCAT(author.login, ' (former employee)') \n           WHEN author.is_bot_user THEN CONCAT(author.login, ' (bot)')\n           ELSE CASE WHEN $show_real_names THEN author.login ELSE author.nickname END\n         END\n      ELSE pr.repository_name \n   END as grouping_field,\n   COUNT(*) as \"PRs count\"\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\nGROUP BY 1\nORDER BY \"PRs count\""
    }
   ]
  },
  {
   "title": "Total changes",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n   CASE WHEN '$group_by_field'='author' \n      THEN\n         CASE \n           WHEN author.is_former_employee THEN CONCAT(author.login, ' (former employee)') \n           WHEN author.is_bot_user THEN CONCAT(author.login, ' (bot)')\n           ELSE CASE WHEN $show_real_names THEN author.login ELSE author.nickname END\n         END\n      ELSE pr.repository_name \n   END as grouping_field,\n   SUM(diff_size) as \"Total diff\"\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\nGROUP BY 1\nORDER BY \"Total diff\""
    }
   ]
  },
  {
   "title": "Average diff size",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "`stinky-socks`",
     "rawSql": "SELECT \n   CASE WHEN '$group_by_field'='author' \n      THEN\n         CASE \n           WHEN author.is_former_employee THEN CONCAT(author.login, ' (former employee)') \n           WHEN author.is_bot_user THEN CONCAT(author.login, ' (bot)')\n           ELSE CASE WHEN $show_real_names THEN author.login ELSE author.nickname END\n         END\n      ELSE pr.repository_name \n   END as grouping_field,\n   AVG(diff_size) as \"Average PR size\"\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\nGROUP BY 1\nORDER BY \"Average PR size\""
    }
   ]
  },
  {
   "title": "Usually got approval in",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "`stinky-socks`",
     "rawSql": "SELECT \n   CASE WHEN '$group_by_field'='author' \n      THEN\n         CASE \n           WHEN author.is_former_employee THEN CONCAT(author.login, ' (former employee)') \n           WHEN author.is_bot_user THEN CONCAT(author.login, ' (bot)')\n           ELSE CASE WHEN $show_real_names THEN author.login ELSE author.nickname END\n         END\n      ELSE pr.repository_name \n   END as grouping_field,\n   AVG(EXTRACT(EPOCH FROM (merged_date-shared_for_review_date))) AS \"Approval speed\" \nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\nGROUP BY 1\nORDER BY \"Approval speed\""
    }
   ]
  },
  {
   "title": "Average reviewers count",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 137 },
   "targets": [
    {
     "dataset": "`stinky-socks`",
     "rawSql": "SELECT \n   CASE WHEN '$group_by_field'='author' \n      THEN\n         CASE \n           WHEN author.is_former_employee THEN CONCAT(author.login, ' (former employee)') \n           WHEN author.is_bot_user THEN CONCAT(author.login, ' (bot)')\n           ELSE CASE WHEN $show_real_names THEN author.login ELSE author.nickname END\n         END\n      ELSE pr.repository_name \n   END as grouping_field,\n   AVG(reviewers_count) AS \"Reviewers count\" \nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\nGROUP BY 1\nORDER BY \"Reviewers count\" "
    }
   ]
  },
  {
   "title": "Usually got comments count",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 137 },
   "targets": [
    {
     "dataset": "`stinky-socks`",
     "rawSql": "SELECT \n   CASE WHEN '$group_by_field'='author' \n      THEN\n         CASE \n           WHEN author.is_former_employee THEN CONCAT(author.login, ' (former employee)') \n           WHEN author.is_bot_user THEN CONCAT(author.login, ' (bot)')\n           ELSE CASE WHEN $show_real_names THEN author.login ELSE author.nickname END\n         END\n      ELSE pr.repository_name \n   END as grouping_field,\n   AVG(total_comments_count) AS \"Comments count\" \nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\nGROUP BY 1\nORDER BY \"Comments count\""
    }
   ]
  },
  {
   "title": "Approval time per PR size",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n   CASE\n      WHEN diff_size<500 THEN 100 * round(diff_size / 100)\n      WHEN diff_size<5000 THEN 1000 * round(diff_size / 1000)\n      WHEN diff_size<50000 THEN 10000 * round(diff_size / 10000)\n      ELSE 50000 * round(diff_size / 50000)\n   END as \"Diff size\",\n   AVG(EXTRACT(EPOCH FROM (merged_date-shared_for_review_date))) AS \"Approval speed\"\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\nGROUP BY 1\nORDER BY \"Diff size\""
    }
   ]
  },
  {
   "title": "Approval time per reviewers count",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 155 },
   "targets": [
    {
     "rawSql": "SELECT\n   reviewers_count  AS \"Reviewers count\",\n    AVG(EXTRACT(EPOCH FROM (merged_date-shared_for_review_date))) AS \"Approval speed\"\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\nGROUP BY reviewers_count\nORDER BY reviewers_count"
    }
   ]
  },
  {
   "title": "Comments count per PR size",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n   CASE\n      WHEN diff_size<500 THEN 100 * round(diff_size / 100)\n      WHEN diff_size<5000 THEN 1000 * round(diff_size / 1000)\n      WHEN diff_size<50000 THEN 10000 * round(diff_size / 10000)\n      ELSE 50000 * round(diff_size / 50000)\n   END as \"Diff size\",\n   AVG(total_comments_count) AS \"Comments count\"\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\nGROUP BY 1\nORDER BY \"Diff size\""
    }
   ]
  },
  {
   "title": "Comments count per reviewers count",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 165 },
   "targets": [
    {
     "rawSql": "SELECT\n   reviewers_count  AS \"Reviewers count\",\n    AVG(total_comments_count) AS \"Comments count\"\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)\nGROUP BY reviewers_count\nORDER BY reviewers_count"
    }
   ]
  },
  { "title": "Raw data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 175 } },
  {
   "title": "Raw PR data",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 176 },
   "targets": [
    {
     "rawSql": "SELECT pr.*, author.nickname, author.is_bot_user, author.is_former_employee\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)"
    }
   ]
  },
  {
   "title": "PRs having integrity errors",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 190 },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(pr.project_name, '/', pr.repository_name, '/', pr.pull_request_number) as pull_request, pr.view_url, pr.integrity_errors\nFROM pull_request AS pr\n   INNER JOIN contributor as author ON author.id = pr.author_id\nWHERE pr.integrity_errors IS NOT NULL\n   AND $__timeFilter(shared_for_review_date) \n   AND (COALESCE($team_name) IS NULL OR pr.team_name IN ($team_name))\n   AND (COALESCE($repository_name) IS NULL OR pr.repository_name IN ($repository_name))\n   AND (COALESCE($pr_author_role) IS NULL OR pr.author_role IN ($pr_author_role))\n   AND (COALESCE($pr_author) IS NULL OR author.id IN ($pr_author))\n   AND ($include_bots_activities OR NOT author.is_bot_user)"
    }
   ]
  }
 ]
}